login_btn="//a[@class='login']",
create_tbox="email_create",
submit_btn="",
mrradio_btn="",
mrsradio_btn="//input[@id='id_gender2']",
fistname_tbox="customer_firstname",
lastname_tbox="customer_lastname",
email="email",
password="passwd"
days_drp="days"
months_drp="months"
years_drp="years"
newsr_dbtn="newsletter"
optrd_btn="optin"
fistname_adr="firstname",
lastname_adr="lastname",
addr_tbox="address1",
city_tbox="city",
post_tbox="postcode",
state_drp="id_state",
country_drp="id_country",
phone_tbox="phone_mobile",
alias_tbox="alias",
register_btn="submitAccount"
myaccount="//span[@class='navigation_page']"
